# Generated by Django 3.1.7 on 2021-03-16 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
