# Generated by Django 3.1.7 on 2021-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='عنوان')),
                ('short_description', models.TextField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='متن')),
                ('image', models.TextField(verbose_name='عکس')),
                ('video', models.TextField(verbose_name='فیلم')),
                ('keywords', models.TextField(max_length=100, verbose_name='کلمات کلیدی')),
                ('meta_description', models.TextField(max_length=200, verbose_name='توضیحات متا')),
                ('slug', models.SlugField(max_length=300, verbose_name='اسلاگ')),
                ('creation_date', models.DateField(verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
