# Generated by Django 3.1.7 on 2021-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=500, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=100, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(max_length=200, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.CharField(max_length=500, verbose_name='فیلم'),
        ),
    ]
